### ISSUE TITLE
A New Power-Up That Gives Points to Player

### ISSUE THREAD

**Issue by Matthew-Maragos** [Matthew-Maragos/Comp-55-Resurrection#1]
A new feature I would like to make for my project is another power-up that gives bonus points to the player who interacts with it.  Doing this I would need to edit these classes in the project: PowerUpType, PowerUp, Player, and Player Manual Pane.  I start by adding the new power-up into PowerUpType class, and after that add it into PowerUp class where I would make my own image for the power-up, have that object act the same as the other power-up objects do (like move the same speed), and edit the randomizer that I have for spawning in the power-ups.  In the Player class, this would include what the power-up does when the player collects it.  For the Player Manual Pane I would have to create a new image to show what the new power-up looks like and what it does.  I'd do that by altering the image that's being used in the project.

**Comment by onzfonz** [comment]
To make this easier, what I would like you to do is to have a couple of things about powerups in a file, so that someone can come in and create new powerups with new images without having to change the code.  You could have a file that stores the name of the powerup image file, and the points that would be given out as a start, and then load that in, so that someone who cannot code can modify the number of powerups that show up in the code merely by modifying the file and replaying the game.  This would make it more general and follow closer to what we want to do with this assignment.
